services:
  - type: web
    name: sbi-backend
    env: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node backend/index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
